"""Generates src/i18n/en.ts (and es.ts from scripts/i18n-es.json) from the t("key", "Default") calls in src."""
import json, pathlib, subprocess, sys

here = pathlib.Path(__file__).resolve().parent
src = here.parent / "src" / "i18n"
extracted = json.loads(subprocess.check_output([sys.executable, str(here / "extract-i18n.py")]))
flat = dict(extracted["keys"])
flat.update(json.loads((here / "i18n-extra-en.json").read_text()))

def nest(d):
    out = {}
    for k in sorted(d):
        cur = out
        parts = k.split(".")
        for p in parts[:-1]:
            cur = cur.setdefault(p, {})
        cur[parts[-1]] = d[k]
    return out

def write(name, var, data, typed):
    body = json.dumps(nest(data), ensure_ascii=False, indent=2)
    head = "// Generated by scripts/gen-i18n.py from the t(\"key\", \"Default\") calls in src. Edit the defaults in code, then re-run.\n"
    if typed:
        text = head + f'import type {{ Messages }} from "./en";\n\nexport const {var}: Messages = {body};\n'
    else:
        text = head + f"export const {var} = {body};\n\ntype Widen<T> = {{ [K in keyof T]: T[K] extends string ? string : Widen<T[K]> }};\nexport type Messages = Widen<typeof {var}>;\n"
    (src / name).write_text(text)

write("en.ts", "en", flat, False)
es_path = here / "i18n-es.json"
if es_path.exists():
    es = json.loads(es_path.read_text())
    missing = sorted(set(flat) - set(es))
    extra = sorted(set(es) - set(flat))
    if missing:
        print("missing es:", len(missing), file=sys.stderr)
        (here / "i18n-es-missing.json").write_text(json.dumps({k: flat[k] for k in missing}, ensure_ascii=False, indent=1))
    write("es.ts", "es", {k: es.get(k, flat[k]) for k in flat}, True)
    if extra:
        print("extra es keys:", extra, file=sys.stderr)
