/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppAssistantRouteImport } from './routes/_app/assistant'
import { Route as AppShippingRouteImport } from './routes/_app/shipping'
import { Route as AcceptInviteInvitationIdRouteImport } from './routes/accept-invite.$invitationId'
import { Route as AppAnalyticsAdSpendRouteImport } from './routes/_app/analytics/ad-spend'
import { Route as AppAnalyticsProfitRouteImport } from './routes/_app/analytics/profit'
import { Route as AppCatalogBlanksRouteImport } from './routes/_app/catalog/blanks'
import { Route as AppCatalogProductsRouteImport } from './routes/_app/catalog/products'
import { Route as AppCatalogSkuMappingRouteImport } from './routes/_app/catalog/sku-mapping'
import { Route as AppDigestsIndexRouteImport } from './routes/_app/digests/index'
import { Route as AppDigestsWeekKeyRouteImport } from './routes/_app/digests/$weekKey'
import { Route as AppInventoryStockRouteImport } from './routes/_app/inventory/stock'
import { Route as AppListingsTrademarkRouteImport } from './routes/_app/listings/trademark'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersOrderIdRouteImport } from './routes/_app/orders/$orderId'
import { Route as AppProductionBinsRouteImport } from './routes/_app/production/bins'
import { Route as AppProductionReprintsRouteImport } from './routes/_app/production/reprints'
import { Route as AppProductionStationsRouteImport } from './routes/_app/production/stations'
import { Route as AppSettingsAuditRouteImport } from './routes/_app/settings/audit'
import { Route as AppSettingsBillingRouteImport } from './routes/_app/settings/billing'
import { Route as AppSettingsChannelsRouteImport } from './routes/_app/settings/channels'
import { Route as AppSettingsCompanyRouteImport } from './routes/_app/settings/company'
import { Route as AppSettingsCostsRouteImport } from './routes/_app/settings/costs'
import { Route as AppSettingsInventoryRouteImport } from './routes/_app/settings/inventory'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app/settings/notifications'
import { Route as AppSettingsShippingRouteImport } from './routes/_app/settings/shipping'
import { Route as AppSettingsStationsRouteImport } from './routes/_app/settings/stations'
import { Route as AppSettingsTeamRouteImport } from './routes/_app/settings/team'
import { Route as AppSettingsVendorsRouteImport } from './routes/_app/settings/vendors'
import { Route as AppVendorIndexRouteImport } from './routes/_app/vendor/index'
import { Route as AppVendorShopsRouteImport } from './routes/_app/vendor/shops'
import { Route as AppCatalogDesignsIndexRouteImport } from './routes/_app/catalog/designs.index'
import { Route as AppCatalogDesignsDesignIdRouteImport } from './routes/_app/catalog/designs.$designId'
import { Route as AppCatalogPersonalizationIndexRouteImport } from './routes/_app/catalog/personalization.index'
import { Route as AppCatalogPersonalizationTemplateIdRouteImport } from './routes/_app/catalog/personalization.$templateId'
import { Route as AppInventoryPurchaseOrdersIndexRouteImport } from './routes/_app/inventory/purchase-orders.index'
import { Route as AppInventoryPurchaseOrdersPoIdRouteImport } from './routes/_app/inventory/purchase-orders.$poId'
import { Route as AppListingsDraftsIndexRouteImport } from './routes/_app/listings/drafts.index'
import { Route as AppListingsDraftsDraftIdRouteImport } from './routes/_app/listings/drafts.$draftId'
import { Route as AppProductionSheetsIndexRouteImport } from './routes/_app/production/sheets.index'
import { Route as AppProductionSheetsSheetIdRouteImport } from './routes/_app/production/sheets.$sheetId'
import { Route as AppVendorSheetsSheetIdRouteImport } from './routes/_app/vendor/sheets.$sheetId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppAssistantRoute = AppAssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppShippingRoute = AppShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppRoute,
} as any)
const AcceptInviteInvitationIdRoute =
  AcceptInviteInvitationIdRouteImport.update({
    id: '/accept-invite/$invitationId',
    path: '/accept-invite/$invitationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAnalyticsAdSpendRoute = AppAnalyticsAdSpendRouteImport.update({
  id: '/analytics/ad-spend',
  path: '/analytics/ad-spend',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsProfitRoute = AppAnalyticsProfitRouteImport.update({
  id: '/analytics/profit',
  path: '/analytics/profit',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogBlanksRoute = AppCatalogBlanksRouteImport.update({
  id: '/catalog/blanks',
  path: '/catalog/blanks',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogProductsRoute = AppCatalogProductsRouteImport.update({
  id: '/catalog/products',
  path: '/catalog/products',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogSkuMappingRoute = AppCatalogSkuMappingRouteImport.update({
  id: '/catalog/sku-mapping',
  path: '/catalog/sku-mapping',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestsIndexRoute = AppDigestsIndexRouteImport.update({
  id: '/digests/',
  path: '/digests/',
  getParentRoute: () => AppRoute,
} as any)
const AppDigestsWeekKeyRoute = AppDigestsWeekKeyRouteImport.update({
  id: '/digests/$weekKey',
  path: '/digests/$weekKey',
  getParentRoute: () => AppRoute,
} as any)
const AppInventoryStockRoute = AppInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsTrademarkRoute = AppListingsTrademarkRouteImport.update({
  id: '/listings/trademark',
  path: '/listings/trademark',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersOrderIdRoute = AppOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionBinsRoute = AppProductionBinsRouteImport.update({
  id: '/production/bins',
  path: '/production/bins',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionReprintsRoute = AppProductionReprintsRouteImport.update({
  id: '/production/reprints',
  path: '/production/reprints',
  getParentRoute: () => AppRoute,
} as any)
const AppProductionStationsRoute = AppProductionStationsRouteImport.update({
  id: '/production/stations',
  path: '/production/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsAuditRoute = AppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsBillingRoute = AppSettingsBillingRouteImport.update({
  id: '/settings/billing',
  path: '/settings/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsChannelsRoute = AppSettingsChannelsRouteImport.update({
  id: '/settings/channels',
  path: '/settings/channels',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCompanyRoute = AppSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsCostsRoute = AppSettingsCostsRouteImport.update({
  id: '/settings/costs',
  path: '/settings/costs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsInventoryRoute = AppSettingsInventoryRouteImport.update({
  id: '/settings/inventory',
  path: '/settings/inventory',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsShippingRoute = AppSettingsShippingRouteImport.update({
  id: '/settings/shipping',
  path: '/settings/shipping',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsStationsRoute = AppSettingsStationsRouteImport.update({
  id: '/settings/stations',
  path: '/settings/stations',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsTeamRoute = AppSettingsTeamRouteImport.update({
  id: '/settings/team',
  path: '/settings/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsVendorsRoute = AppSettingsVendorsRouteImport.update({
  id: '/settings/vendors',
  path: '/settings/vendors',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorIndexRoute = AppVendorIndexRouteImport.update({
  id: '/vendor/',
  path: '/vendor/',
  getParentRoute: () => AppRoute,
} as any)
const AppVendorShopsRoute = AppVendorShopsRouteImport.update({
  id: '/vendor/shops',
  path: '/vendor/shops',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogDesignsIndexRoute = AppCatalogDesignsIndexRouteImport.update({
  id: '/catalog/designs/',
  path: '/catalog/designs/',
  getParentRoute: () => AppRoute,
} as any)
const AppCatalogDesignsDesignIdRoute =
  AppCatalogDesignsDesignIdRouteImport.update({
    id: '/catalog/designs/$designId',
    path: '/catalog/designs/$designId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogPersonalizationIndexRoute =
  AppCatalogPersonalizationIndexRouteImport.update({
    id: '/catalog/personalization/',
    path: '/catalog/personalization/',
    getParentRoute: () => AppRoute,
  } as any)
const AppCatalogPersonalizationTemplateIdRoute =
  AppCatalogPersonalizationTemplateIdRouteImport.update({
    id: '/catalog/personalization/$templateId',
    path: '/catalog/personalization/$templateId',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryPurchaseOrdersIndexRoute =
  AppInventoryPurchaseOrdersIndexRouteImport.update({
    id: '/inventory/purchase-orders/',
    path: '/inventory/purchase-orders/',
    getParentRoute: () => AppRoute,
  } as any)
const AppInventoryPurchaseOrdersPoIdRoute =
  AppInventoryPurchaseOrdersPoIdRouteImport.update({
    id: '/inventory/purchase-orders/$poId',
    path: '/inventory/purchase-orders/$poId',
    getParentRoute: () => AppRoute,
  } as any)
const AppListingsDraftsIndexRoute = AppListingsDraftsIndexRouteImport.update({
  id: '/listings/drafts/',
  path: '/listings/drafts/',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsDraftsDraftIdRoute =
  AppListingsDraftsDraftIdRouteImport.update({
    id: '/listings/drafts/$draftId',
    path: '/listings/drafts/$draftId',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductionSheetsIndexRoute =
  AppProductionSheetsIndexRouteImport.update({
    id: '/production/sheets/',
    path: '/production/sheets/',
    getParentRoute: () => AppRoute,
  } as any)
const AppProductionSheetsSheetIdRoute =
  AppProductionSheetsSheetIdRouteImport.update({
    id: '/production/sheets/$sheetId',
    path: '/production/sheets/$sheetId',
    getParentRoute: () => AppRoute,
  } as any)
const AppVendorSheetsSheetIdRoute = AppVendorSheetsSheetIdRouteImport.update({
  id: '/vendor/sheets/$sheetId',
  path: '/vendor/sheets/$sheetId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/assistant': typeof AppAssistantRoute
  '/shipping': typeof AppShippingRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/analytics/ad-spend': typeof AppAnalyticsAdSpendRoute
  '/analytics/profit': typeof AppAnalyticsProfitRoute
  '/catalog/blanks': typeof AppCatalogBlanksRoute
  '/catalog/products': typeof AppCatalogProductsRoute
  '/catalog/sku-mapping': typeof AppCatalogSkuMappingRoute
  '/digests/$weekKey': typeof AppDigestsWeekKeyRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/listings/trademark': typeof AppListingsTrademarkRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/production/bins': typeof AppProductionBinsRoute
  '/production/reprints': typeof AppProductionReprintsRoute
  '/production/stations': typeof AppProductionStationsRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/costs': typeof AppSettingsCostsRoute
  '/settings/inventory': typeof AppSettingsInventoryRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/stations': typeof AppSettingsStationsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/vendors': typeof AppSettingsVendorsRoute
  '/vendor/shops': typeof AppVendorShopsRoute
  '/digests/': typeof AppDigestsIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/vendor/': typeof AppVendorIndexRoute
  '/catalog/designs/$designId': typeof AppCatalogDesignsDesignIdRoute
  '/catalog/personalization/$templateId': typeof AppCatalogPersonalizationTemplateIdRoute
  '/inventory/purchase-orders/$poId': typeof AppInventoryPurchaseOrdersPoIdRoute
  '/listings/drafts/$draftId': typeof AppListingsDraftsDraftIdRoute
  '/production/sheets/$sheetId': typeof AppProductionSheetsSheetIdRoute
  '/vendor/sheets/$sheetId': typeof AppVendorSheetsSheetIdRoute
  '/catalog/designs/': typeof AppCatalogDesignsIndexRoute
  '/catalog/personalization/': typeof AppCatalogPersonalizationIndexRoute
  '/inventory/purchase-orders/': typeof AppInventoryPurchaseOrdersIndexRoute
  '/listings/drafts/': typeof AppListingsDraftsIndexRoute
  '/production/sheets/': typeof AppProductionSheetsIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/account': typeof AppAccountRoute
  '/assistant': typeof AppAssistantRoute
  '/shipping': typeof AppShippingRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/': typeof AppIndexRoute
  '/analytics/ad-spend': typeof AppAnalyticsAdSpendRoute
  '/analytics/profit': typeof AppAnalyticsProfitRoute
  '/catalog/blanks': typeof AppCatalogBlanksRoute
  '/catalog/products': typeof AppCatalogProductsRoute
  '/catalog/sku-mapping': typeof AppCatalogSkuMappingRoute
  '/digests/$weekKey': typeof AppDigestsWeekKeyRoute
  '/inventory/stock': typeof AppInventoryStockRoute
  '/listings/trademark': typeof AppListingsTrademarkRoute
  '/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/production/bins': typeof AppProductionBinsRoute
  '/production/reprints': typeof AppProductionReprintsRoute
  '/production/stations': typeof AppProductionStationsRoute
  '/settings/audit': typeof AppSettingsAuditRoute
  '/settings/billing': typeof AppSettingsBillingRoute
  '/settings/channels': typeof AppSettingsChannelsRoute
  '/settings/company': typeof AppSettingsCompanyRoute
  '/settings/costs': typeof AppSettingsCostsRoute
  '/settings/inventory': typeof AppSettingsInventoryRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/shipping': typeof AppSettingsShippingRoute
  '/settings/stations': typeof AppSettingsStationsRoute
  '/settings/team': typeof AppSettingsTeamRoute
  '/settings/vendors': typeof AppSettingsVendorsRoute
  '/vendor/shops': typeof AppVendorShopsRoute
  '/digests': typeof AppDigestsIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/vendor': typeof AppVendorIndexRoute
  '/catalog/designs/$designId': typeof AppCatalogDesignsDesignIdRoute
  '/catalog/personalization/$templateId': typeof AppCatalogPersonalizationTemplateIdRoute
  '/inventory/purchase-orders/$poId': typeof AppInventoryPurchaseOrdersPoIdRoute
  '/listings/drafts/$draftId': typeof AppListingsDraftsDraftIdRoute
  '/production/sheets/$sheetId': typeof AppProductionSheetsSheetIdRoute
  '/vendor/sheets/$sheetId': typeof AppVendorSheetsSheetIdRoute
  '/catalog/designs': typeof AppCatalogDesignsIndexRoute
  '/catalog/personalization': typeof AppCatalogPersonalizationIndexRoute
  '/inventory/purchase-orders': typeof AppInventoryPurchaseOrdersIndexRoute
  '/listings/drafts': typeof AppListingsDraftsIndexRoute
  '/production/sheets': typeof AppProductionSheetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/assistant': typeof AppAssistantRoute
  '/_app/shipping': typeof AppShippingRoute
  '/accept-invite/$invitationId': typeof AcceptInviteInvitationIdRoute
  '/_app/': typeof AppIndexRoute
  '/_app/analytics/ad-spend': typeof AppAnalyticsAdSpendRoute
  '/_app/analytics/profit': typeof AppAnalyticsProfitRoute
  '/_app/catalog/blanks': typeof AppCatalogBlanksRoute
  '/_app/catalog/products': typeof AppCatalogProductsRoute
  '/_app/catalog/sku-mapping': typeof AppCatalogSkuMappingRoute
  '/_app/digests/$weekKey': typeof AppDigestsWeekKeyRoute
  '/_app/inventory/stock': typeof AppInventoryStockRoute
  '/_app/listings/trademark': typeof AppListingsTrademarkRoute
  '/_app/orders/$orderId': typeof AppOrdersOrderIdRoute
  '/_app/production/bins': typeof AppProductionBinsRoute
  '/_app/production/reprints': typeof AppProductionReprintsRoute
  '/_app/production/stations': typeof AppProductionStationsRoute
  '/_app/settings/audit': typeof AppSettingsAuditRoute
  '/_app/settings/billing': typeof AppSettingsBillingRoute
  '/_app/settings/channels': typeof AppSettingsChannelsRoute
  '/_app/settings/company': typeof AppSettingsCompanyRoute
  '/_app/settings/costs': typeof AppSettingsCostsRoute
  '/_app/settings/inventory': typeof AppSettingsInventoryRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/shipping': typeof AppSettingsShippingRoute
  '/_app/settings/stations': typeof AppSettingsStationsRoute
  '/_app/settings/team': typeof AppSettingsTeamRoute
  '/_app/settings/vendors': typeof AppSettingsVendorsRoute
  '/_app/vendor/shops': typeof AppVendorShopsRoute
  '/_app/digests/': typeof AppDigestsIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/vendor/': typeof AppVendorIndexRoute
  '/_app/catalog/designs/$designId': typeof AppCatalogDesignsDesignIdRoute
  '/_app/catalog/personalization/$templateId': typeof AppCatalogPersonalizationTemplateIdRoute
  '/_app/inventory/purchase-orders/$poId': typeof AppInventoryPurchaseOrdersPoIdRoute
  '/_app/listings/drafts/$draftId': typeof AppListingsDraftsDraftIdRoute
  '/_app/production/sheets/$sheetId': typeof AppProductionSheetsSheetIdRoute
  '/_app/vendor/sheets/$sheetId': typeof AppVendorSheetsSheetIdRoute
  '/_app/catalog/designs/': typeof AppCatalogDesignsIndexRoute
  '/_app/catalog/personalization/': typeof AppCatalogPersonalizationIndexRoute
  '/_app/inventory/purchase-orders/': typeof AppInventoryPurchaseOrdersIndexRoute
  '/_app/listings/drafts/': typeof AppListingsDraftsIndexRoute
  '/_app/production/sheets/': typeof AppProductionSheetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/assistant'
    | '/shipping'
    | '/accept-invite/$invitationId'
    | '/analytics/ad-spend'
    | '/analytics/profit'
    | '/catalog/blanks'
    | '/catalog/products'
    | '/catalog/sku-mapping'
    | '/digests/$weekKey'
    | '/inventory/stock'
    | '/listings/trademark'
    | '/orders/$orderId'
    | '/production/bins'
    | '/production/reprints'
    | '/production/stations'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/company'
    | '/settings/costs'
    | '/settings/inventory'
    | '/settings/notifications'
    | '/settings/shipping'
    | '/settings/stations'
    | '/settings/team'
    | '/settings/vendors'
    | '/vendor/shops'
    | '/digests/'
    | '/orders/'
    | '/vendor/'
    | '/catalog/designs/$designId'
    | '/catalog/personalization/$templateId'
    | '/inventory/purchase-orders/$poId'
    | '/listings/drafts/$draftId'
    | '/production/sheets/$sheetId'
    | '/vendor/sheets/$sheetId'
    | '/catalog/designs/'
    | '/catalog/personalization/'
    | '/inventory/purchase-orders/'
    | '/listings/drafts/'
    | '/production/sheets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/account'
    | '/assistant'
    | '/shipping'
    | '/accept-invite/$invitationId'
    | '/'
    | '/analytics/ad-spend'
    | '/analytics/profit'
    | '/catalog/blanks'
    | '/catalog/products'
    | '/catalog/sku-mapping'
    | '/digests/$weekKey'
    | '/inventory/stock'
    | '/listings/trademark'
    | '/orders/$orderId'
    | '/production/bins'
    | '/production/reprints'
    | '/production/stations'
    | '/settings/audit'
    | '/settings/billing'
    | '/settings/channels'
    | '/settings/company'
    | '/settings/costs'
    | '/settings/inventory'
    | '/settings/notifications'
    | '/settings/shipping'
    | '/settings/stations'
    | '/settings/team'
    | '/settings/vendors'
    | '/vendor/shops'
    | '/digests'
    | '/orders'
    | '/vendor'
    | '/catalog/designs/$designId'
    | '/catalog/personalization/$templateId'
    | '/inventory/purchase-orders/$poId'
    | '/listings/drafts/$draftId'
    | '/production/sheets/$sheetId'
    | '/vendor/sheets/$sheetId'
    | '/catalog/designs'
    | '/catalog/personalization'
    | '/inventory/purchase-orders'
    | '/listings/drafts'
    | '/production/sheets'
  id:
    | '__root__'
    | '/_app'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/unsubscribe'
    | '/verify-email'
    | '/_app/account'
    | '/_app/assistant'
    | '/_app/shipping'
    | '/accept-invite/$invitationId'
    | '/_app/'
    | '/_app/analytics/ad-spend'
    | '/_app/analytics/profit'
    | '/_app/catalog/blanks'
    | '/_app/catalog/products'
    | '/_app/catalog/sku-mapping'
    | '/_app/digests/$weekKey'
    | '/_app/inventory/stock'
    | '/_app/listings/trademark'
    | '/_app/orders/$orderId'
    | '/_app/production/bins'
    | '/_app/production/reprints'
    | '/_app/production/stations'
    | '/_app/settings/audit'
    | '/_app/settings/billing'
    | '/_app/settings/channels'
    | '/_app/settings/company'
    | '/_app/settings/costs'
    | '/_app/settings/inventory'
    | '/_app/settings/notifications'
    | '/_app/settings/shipping'
    | '/_app/settings/stations'
    | '/_app/settings/team'
    | '/_app/settings/vendors'
    | '/_app/vendor/shops'
    | '/_app/digests/'
    | '/_app/orders/'
    | '/_app/vendor/'
    | '/_app/catalog/designs/$designId'
    | '/_app/catalog/personalization/$templateId'
    | '/_app/inventory/purchase-orders/$poId'
    | '/_app/listings/drafts/$draftId'
    | '/_app/production/sheets/$sheetId'
    | '/_app/vendor/sheets/$sheetId'
    | '/_app/catalog/designs/'
    | '/_app/catalog/personalization/'
    | '/_app/inventory/purchase-orders/'
    | '/_app/listings/drafts/'
    | '/_app/production/sheets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AcceptInviteInvitationIdRoute: typeof AcceptInviteInvitationIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assistant': {
      id: '/_app/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AppAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipping': {
      id: '/_app/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AppShippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/accept-invite/$invitationId': {
      id: '/accept-invite/$invitationId'
      path: '/accept-invite/$invitationId'
      fullPath: '/accept-invite/$invitationId'
      preLoaderRoute: typeof AcceptInviteInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/analytics/ad-spend': {
      id: '/_app/analytics/ad-spend'
      path: '/analytics/ad-spend'
      fullPath: '/analytics/ad-spend'
      preLoaderRoute: typeof AppAnalyticsAdSpendRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics/profit': {
      id: '/_app/analytics/profit'
      path: '/analytics/profit'
      fullPath: '/analytics/profit'
      preLoaderRoute: typeof AppAnalyticsProfitRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/blanks': {
      id: '/_app/catalog/blanks'
      path: '/catalog/blanks'
      fullPath: '/catalog/blanks'
      preLoaderRoute: typeof AppCatalogBlanksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/products': {
      id: '/_app/catalog/products'
      path: '/catalog/products'
      fullPath: '/catalog/products'
      preLoaderRoute: typeof AppCatalogProductsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/sku-mapping': {
      id: '/_app/catalog/sku-mapping'
      path: '/catalog/sku-mapping'
      fullPath: '/catalog/sku-mapping'
      preLoaderRoute: typeof AppCatalogSkuMappingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digests/': {
      id: '/_app/digests/'
      path: '/digests'
      fullPath: '/digests/'
      preLoaderRoute: typeof AppDigestsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/digests/$weekKey': {
      id: '/_app/digests/$weekKey'
      path: '/digests/$weekKey'
      fullPath: '/digests/$weekKey'
      preLoaderRoute: typeof AppDigestsWeekKeyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/stock': {
      id: '/_app/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AppInventoryStockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/trademark': {
      id: '/_app/listings/trademark'
      path: '/listings/trademark'
      fullPath: '/listings/trademark'
      preLoaderRoute: typeof AppListingsTrademarkRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$orderId': {
      id: '/_app/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/orders/$orderId'
      preLoaderRoute: typeof AppOrdersOrderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/bins': {
      id: '/_app/production/bins'
      path: '/production/bins'
      fullPath: '/production/bins'
      preLoaderRoute: typeof AppProductionBinsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/reprints': {
      id: '/_app/production/reprints'
      path: '/production/reprints'
      fullPath: '/production/reprints'
      preLoaderRoute: typeof AppProductionReprintsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/stations': {
      id: '/_app/production/stations'
      path: '/production/stations'
      fullPath: '/production/stations'
      preLoaderRoute: typeof AppProductionStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/audit': {
      id: '/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/settings/audit'
      preLoaderRoute: typeof AppSettingsAuditRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/billing': {
      id: '/_app/settings/billing'
      path: '/settings/billing'
      fullPath: '/settings/billing'
      preLoaderRoute: typeof AppSettingsBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/channels': {
      id: '/_app/settings/channels'
      path: '/settings/channels'
      fullPath: '/settings/channels'
      preLoaderRoute: typeof AppSettingsChannelsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/company': {
      id: '/_app/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AppSettingsCompanyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/costs': {
      id: '/_app/settings/costs'
      path: '/settings/costs'
      fullPath: '/settings/costs'
      preLoaderRoute: typeof AppSettingsCostsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/inventory': {
      id: '/_app/settings/inventory'
      path: '/settings/inventory'
      fullPath: '/settings/inventory'
      preLoaderRoute: typeof AppSettingsInventoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/shipping': {
      id: '/_app/settings/shipping'
      path: '/settings/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof AppSettingsShippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/stations': {
      id: '/_app/settings/stations'
      path: '/settings/stations'
      fullPath: '/settings/stations'
      preLoaderRoute: typeof AppSettingsStationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/team': {
      id: '/_app/settings/team'
      path: '/settings/team'
      fullPath: '/settings/team'
      preLoaderRoute: typeof AppSettingsTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/vendors': {
      id: '/_app/settings/vendors'
      path: '/settings/vendors'
      fullPath: '/settings/vendors'
      preLoaderRoute: typeof AppSettingsVendorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/': {
      id: '/_app/vendor/'
      path: '/vendor'
      fullPath: '/vendor/'
      preLoaderRoute: typeof AppVendorIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/shops': {
      id: '/_app/vendor/shops'
      path: '/vendor/shops'
      fullPath: '/vendor/shops'
      preLoaderRoute: typeof AppVendorShopsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/designs/': {
      id: '/_app/catalog/designs/'
      path: '/catalog/designs'
      fullPath: '/catalog/designs/'
      preLoaderRoute: typeof AppCatalogDesignsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/designs/$designId': {
      id: '/_app/catalog/designs/$designId'
      path: '/catalog/designs/$designId'
      fullPath: '/catalog/designs/$designId'
      preLoaderRoute: typeof AppCatalogDesignsDesignIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/personalization/': {
      id: '/_app/catalog/personalization/'
      path: '/catalog/personalization'
      fullPath: '/catalog/personalization/'
      preLoaderRoute: typeof AppCatalogPersonalizationIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/catalog/personalization/$templateId': {
      id: '/_app/catalog/personalization/$templateId'
      path: '/catalog/personalization/$templateId'
      fullPath: '/catalog/personalization/$templateId'
      preLoaderRoute: typeof AppCatalogPersonalizationTemplateIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/purchase-orders/': {
      id: '/_app/inventory/purchase-orders/'
      path: '/inventory/purchase-orders'
      fullPath: '/inventory/purchase-orders/'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inventory/purchase-orders/$poId': {
      id: '/_app/inventory/purchase-orders/$poId'
      path: '/inventory/purchase-orders/$poId'
      fullPath: '/inventory/purchase-orders/$poId'
      preLoaderRoute: typeof AppInventoryPurchaseOrdersPoIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/drafts/': {
      id: '/_app/listings/drafts/'
      path: '/listings/drafts'
      fullPath: '/listings/drafts/'
      preLoaderRoute: typeof AppListingsDraftsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings/drafts/$draftId': {
      id: '/_app/listings/drafts/$draftId'
      path: '/listings/drafts/$draftId'
      fullPath: '/listings/drafts/$draftId'
      preLoaderRoute: typeof AppListingsDraftsDraftIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/sheets/': {
      id: '/_app/production/sheets/'
      path: '/production/sheets'
      fullPath: '/production/sheets/'
      preLoaderRoute: typeof AppProductionSheetsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/production/sheets/$sheetId': {
      id: '/_app/production/sheets/$sheetId'
      path: '/production/sheets/$sheetId'
      fullPath: '/production/sheets/$sheetId'
      preLoaderRoute: typeof AppProductionSheetsSheetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/vendor/sheets/$sheetId': {
      id: '/_app/vendor/sheets/$sheetId'
      path: '/vendor/sheets/$sheetId'
      fullPath: '/vendor/sheets/$sheetId'
      preLoaderRoute: typeof AppVendorSheetsSheetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppAssistantRoute: typeof AppAssistantRoute
  AppShippingRoute: typeof AppShippingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsAdSpendRoute: typeof AppAnalyticsAdSpendRoute
  AppAnalyticsProfitRoute: typeof AppAnalyticsProfitRoute
  AppCatalogBlanksRoute: typeof AppCatalogBlanksRoute
  AppCatalogProductsRoute: typeof AppCatalogProductsRoute
  AppCatalogSkuMappingRoute: typeof AppCatalogSkuMappingRoute
  AppDigestsWeekKeyRoute: typeof AppDigestsWeekKeyRoute
  AppInventoryStockRoute: typeof AppInventoryStockRoute
  AppListingsTrademarkRoute: typeof AppListingsTrademarkRoute
  AppOrdersOrderIdRoute: typeof AppOrdersOrderIdRoute
  AppProductionBinsRoute: typeof AppProductionBinsRoute
  AppProductionReprintsRoute: typeof AppProductionReprintsRoute
  AppProductionStationsRoute: typeof AppProductionStationsRoute
  AppSettingsAuditRoute: typeof AppSettingsAuditRoute
  AppSettingsBillingRoute: typeof AppSettingsBillingRoute
  AppSettingsChannelsRoute: typeof AppSettingsChannelsRoute
  AppSettingsCompanyRoute: typeof AppSettingsCompanyRoute
  AppSettingsCostsRoute: typeof AppSettingsCostsRoute
  AppSettingsInventoryRoute: typeof AppSettingsInventoryRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsShippingRoute: typeof AppSettingsShippingRoute
  AppSettingsStationsRoute: typeof AppSettingsStationsRoute
  AppSettingsTeamRoute: typeof AppSettingsTeamRoute
  AppSettingsVendorsRoute: typeof AppSettingsVendorsRoute
  AppVendorShopsRoute: typeof AppVendorShopsRoute
  AppDigestsIndexRoute: typeof AppDigestsIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppVendorIndexRoute: typeof AppVendorIndexRoute
  AppCatalogDesignsDesignIdRoute: typeof AppCatalogDesignsDesignIdRoute
  AppCatalogPersonalizationTemplateIdRoute: typeof AppCatalogPersonalizationTemplateIdRoute
  AppInventoryPurchaseOrdersPoIdRoute: typeof AppInventoryPurchaseOrdersPoIdRoute
  AppListingsDraftsDraftIdRoute: typeof AppListingsDraftsDraftIdRoute
  AppProductionSheetsSheetIdRoute: typeof AppProductionSheetsSheetIdRoute
  AppVendorSheetsSheetIdRoute: typeof AppVendorSheetsSheetIdRoute
  AppCatalogDesignsIndexRoute: typeof AppCatalogDesignsIndexRoute
  AppCatalogPersonalizationIndexRoute: typeof AppCatalogPersonalizationIndexRoute
  AppInventoryPurchaseOrdersIndexRoute: typeof AppInventoryPurchaseOrdersIndexRoute
  AppListingsDraftsIndexRoute: typeof AppListingsDraftsIndexRoute
  AppProductionSheetsIndexRoute: typeof AppProductionSheetsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppAssistantRoute: AppAssistantRoute,
  AppShippingRoute: AppShippingRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsAdSpendRoute: AppAnalyticsAdSpendRoute,
  AppAnalyticsProfitRoute: AppAnalyticsProfitRoute,
  AppCatalogBlanksRoute: AppCatalogBlanksRoute,
  AppCatalogProductsRoute: AppCatalogProductsRoute,
  AppCatalogSkuMappingRoute: AppCatalogSkuMappingRoute,
  AppDigestsWeekKeyRoute: AppDigestsWeekKeyRoute,
  AppInventoryStockRoute: AppInventoryStockRoute,
  AppListingsTrademarkRoute: AppListingsTrademarkRoute,
  AppOrdersOrderIdRoute: AppOrdersOrderIdRoute,
  AppProductionBinsRoute: AppProductionBinsRoute,
  AppProductionReprintsRoute: AppProductionReprintsRoute,
  AppProductionStationsRoute: AppProductionStationsRoute,
  AppSettingsAuditRoute: AppSettingsAuditRoute,
  AppSettingsBillingRoute: AppSettingsBillingRoute,
  AppSettingsChannelsRoute: AppSettingsChannelsRoute,
  AppSettingsCompanyRoute: AppSettingsCompanyRoute,
  AppSettingsCostsRoute: AppSettingsCostsRoute,
  AppSettingsInventoryRoute: AppSettingsInventoryRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsShippingRoute: AppSettingsShippingRoute,
  AppSettingsStationsRoute: AppSettingsStationsRoute,
  AppSettingsTeamRoute: AppSettingsTeamRoute,
  AppSettingsVendorsRoute: AppSettingsVendorsRoute,
  AppVendorShopsRoute: AppVendorShopsRoute,
  AppDigestsIndexRoute: AppDigestsIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppVendorIndexRoute: AppVendorIndexRoute,
  AppCatalogDesignsDesignIdRoute: AppCatalogDesignsDesignIdRoute,
  AppCatalogPersonalizationTemplateIdRoute:
    AppCatalogPersonalizationTemplateIdRoute,
  AppInventoryPurchaseOrdersPoIdRoute: AppInventoryPurchaseOrdersPoIdRoute,
  AppListingsDraftsDraftIdRoute: AppListingsDraftsDraftIdRoute,
  AppProductionSheetsSheetIdRoute: AppProductionSheetsSheetIdRoute,
  AppVendorSheetsSheetIdRoute: AppVendorSheetsSheetIdRoute,
  AppCatalogDesignsIndexRoute: AppCatalogDesignsIndexRoute,
  AppCatalogPersonalizationIndexRoute: AppCatalogPersonalizationIndexRoute,
  AppInventoryPurchaseOrdersIndexRoute: AppInventoryPurchaseOrdersIndexRoute,
  AppListingsDraftsIndexRoute: AppListingsDraftsIndexRoute,
  AppProductionSheetsIndexRoute: AppProductionSheetsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AcceptInviteInvitationIdRoute: AcceptInviteInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
