/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as GangSheetsRouteImport } from './routes/gang-sheets'
import { Route as InventoryRouteImport } from './routes/inventory'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ShippingRouteImport } from './routes/shipping'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const GangSheetsRoute = GangSheetsRouteImport.update({
  id: '/gang-sheets',
  path: '/gang-sheets',
  getParentRoute: () => rootRouteImport,
} as any)
const InventoryRoute = InventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/gang-sheets': typeof GangSheetsRoute
  '/inventory': typeof InventoryRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/gang-sheets': typeof GangSheetsRoute
  '/inventory': typeof InventoryRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/assistant': typeof AssistantRoute
  '/gang-sheets': typeof GangSheetsRoute
  '/inventory': typeof InventoryRoute
  '/listings': typeof ListingsRoute
  '/orders': typeof OrdersRoute
  '/production': typeof ProductionRoute
  '/settings': typeof SettingsRoute
  '/shipping': typeof ShippingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/gang-sheets'
    | '/inventory'
    | '/listings'
    | '/orders'
    | '/production'
    | '/settings'
    | '/shipping'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/assistant'
    | '/gang-sheets'
    | '/inventory'
    | '/listings'
    | '/orders'
    | '/production'
    | '/settings'
    | '/shipping'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/assistant'
    | '/gang-sheets'
    | '/inventory'
    | '/listings'
    | '/orders'
    | '/production'
    | '/settings'
    | '/shipping'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AssistantRoute: typeof AssistantRoute
  GangSheetsRoute: typeof GangSheetsRoute
  InventoryRoute: typeof InventoryRoute
  ListingsRoute: typeof ListingsRoute
  OrdersRoute: typeof OrdersRoute
  ProductionRoute: typeof ProductionRoute
  SettingsRoute: typeof SettingsRoute
  ShippingRoute: typeof ShippingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gang-sheets': {
      id: '/gang-sheets'
      path: '/gang-sheets'
      fullPath: '/gang-sheets'
      preLoaderRoute: typeof GangSheetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventory': {
      id: '/inventory'
      path: '/inventory'
      fullPath: '/inventory'
      preLoaderRoute: typeof InventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AssistantRoute: AssistantRoute,
  GangSheetsRoute: GangSheetsRoute,
  InventoryRoute: InventoryRoute,
  ListingsRoute: ListingsRoute,
  OrdersRoute: OrdersRoute,
  ProductionRoute: ProductionRoute,
  SettingsRoute: SettingsRoute,
  ShippingRoute: ShippingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
